---

- hosts: web
  become: yes
  tasks:
    - name: Install nginx on ubuntu
      apt: name=nginx state=latest update_cache=yes
      register: installed
      notify: 
         - restart service


    - name: Print value
      debug: var=installed

  handlers:  
    - name: restart service
      service: name=nginx enabled=true state=restarted
      when: installed is succeeded
   



    
